name: CMake Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build-type: [Debug, Release]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies on Linux
      if: runner.os == 'ubuntu-latest'
      run: |
        sudo apt-get update || true
        sudo apt-get install -y cmake libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libudev-dev
        # Проверяем наличие UDev
        ls /usr/include/libudev.h || echo "libudev.h not found"
        ls /usr/lib/x86_64-linux-gnu/libudev.so || echo "libudev.so not found"

    - name: Install CMake on Windows
      if: runner.os == 'windows-latest'
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: '3.25.0'

    - name: Install dependencies on macOS
      if: runner.os == 'macos-latest'
      run: |
        brew update
        brew install cmake

    - name: Configure CMake
      run: |
        cmake -S . -B build \
          -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} \
          -DUDEV_PATH_INCLUDES=/usr/include \
          -DUDEV_PATH_LIB=/usr/lib/x86_64-linux-gnu/libudev.so \
          -DOPENGL_gl_LIBRARY=/usr/lib/x86_64-linux-gnu/libGL.so \
          -DOPENGL_INCLUDE_DIR=/usr/include/GL

    - name: Build with CMake
      run: cmake --build build --config ${{ matrix.build-type }}
