name: CMake Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]  # Убрали Linux
        build-type: [Debug, Release]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install CMake on Windows
      if: runner.os == 'windows-latest'
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: '3.25.0'

    - name: Install dependencies on macOS
      if: runner.os == 'macos-latest'
      run: |
        brew update
        brew install cmake

    - name: Configure CMake
      run: |
        cmake -S . -B build \
          -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}

    - name: Build with CMake
      run: cmake --build build --config ${{ matrix.build-type }}
