name: Windows Build with MinGW

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install MinGW
      run: |
        choco install mingw -y
        refreshenv

    - name: Add MinGW to PATH
      run: |
        echo "::add-path::C:\tools\mingw64\bin"

    - name: Configure CMake with MinGW
      run: |
        cmake -S . -B build -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release

    - name: Build with MinGW
      run: |
        cmake --build build --config Release
