name: CMake Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        build-type: [Debug]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies on Linux
      if: runner.os == 'ubuntu-latest'
      run: |
        sudo apt-get update || true
        sudo apt-get install -y cmake libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libudev-dev

    - name: Configure CMake
      run: |
        cmake -S . -B build \
          -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} \
          -DOPENGL_gl_LIBRARY=/usr/lib/x86_64-linux-gnu/libGL.so \
          -DOPENGL_glx_LIBRARY=/usr/lib/x86_64-linux-gnu/libGLX.so \
          -DOPENGL_INCLUDE_DIR=/usr/include

    - name: Build with CMake
      run: cmake --build build --config ${{ matrix.build-type }}
